### ISSUE TITLE
setEmail on null when using using guest checkout

### ISSUE THREAD

**Issue by nfourtythree** [KuriousAgency/commerce-admin-orders#9]
https://github.com/KuriousAgency/commerce-admin-orders/blob/e9657a005a8430a81ba466f306c50b8990d5c583/src/controllers/OrdersController.php#L209

That line is the offending line, as basically the `$order` variable is null.

**Comment by mcjackson18** [comment]
Hi @nfourtythree, a new order is created as soon as the "New Order" button is clicked, this is passed through to the orders/update-user action via the orderNumber param.

As a new order should always exist It would be good to understand why `$order` is coming back as null on line 209.

- Is the error intermittent or shown for every new order?
- Is this happening if you select an existing user instead of guest checkout

**Comment by nfourtythree** [comment]
Hey @mcjackson18 

Will take another look and see if I cant create a reliable replication of the error for testing
